export const SET_AUTH = 'SET_AUTH';

export const LOAD_INITIAL_USERS = 'LOAD_INITIAL_USERS';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DESTROY_USER = 'DESTROY_USER';

export const LOAD_INITIAL_TRANSACTIONS = 'LOAD_INITIAL_TRANSACTIONS';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';

export const CREATE_LINE_ITEM = 'CREATE_LINE_ITEM';
export const UPDATE_LINE_ITEM = 'UPDATE_LINE_ITEM';
export const DELETE_LINE_ITEM  = 'DELETE_LINE_ITEM ';

export const LOAD_INITIAL_STOCKS = 'LOAD_INITIAL_STOCKS';